spring.application.name=boxly-backend
spring.datasource.url=jdbc:postgresql://localhost:5432/boxly
spring.datasource.username=postgres
spring.datasource.password=Cms@2025
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

spring.security.oauth2.resourceserver.jwt.issuer-uri=http://192.168.12.85:8080/realms/master
spring.security.oauth2.resourceserver.jwt.jwk-set-uri=${spring.security.oauth2.resourceserver.jwt.issuer-uri}/protocol/openid-connect/certs
server.port=8080
# JWT Configuration
jwt.auth.converter.resource-id=boxly-backend
jwt.auth.converter.principal-attribute=preferred_username
keycloak.auth-server-url=http://192.168.12.85:8080/
keycloak.realm=master
keycloak.client-id=boxly-backend
keycloak.client-secret=oCB6GfOVG7mvhE1lED9FWytKoDw2UkMb
rhna.api.base-url=https://rhna.cmscompany.net/APIQualiso
rhna.api.employees-path=/employes
rhna.api.postes-path=/postes
logging.level.org.springframework.security=DEBUG
